---
kind: pipeline
type: docker
name: Check Version

trigger:
  event:
  - custom

steps:
  - name: Check Dockerhub Nextcloud Version
    image: fuzzymistborn/docker-alpine-skopeo:latest
    commands:
      - /bin/sh /drone/src/update.sh

  - name: Push Commit
    image: drone/git
    commands:
      - git add .
      - git commit -m "[CI] Update Dockerfile to lateset NC version"
      - git push origin main

  - name: Send TG Notification
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: tg_token
      to:
        from_secret: tg_id
      format: markdown
      message: "❌  Nextcloud Docker Updater Task has *FAILED*!\n🌐  [Output]({{build.link}})"
    when:
      status: [ failure ]

---
kind: pipeline
type: docker
name: Generate Tags


trigger:
  event:
  - cron
  cron:
  - nightly
steps:
  - name: Generate Tag
    image: appleboy/drone-git-push
    commands:
      - dockerver=$( cat docker_ver )
      - git tag -a $dockerver -m "Nextcloud Release v. $dockerver"
      - git push origin main $dockerver

---
kind: pipeline
type: docker
name: Build Docker

trigger:
  event:
  - tag

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock

steps:
- name: Build and push release
  image: fuzzymistborn/docker-alpine-skopeo:latest
  environment:
    DOCKERHUB_PASS:
      from_secret: dockerhub_pw
    GHCR_PASS:
      from_secret: ghcr_pw
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock
  commands:
    - NC_FULLVER=$( cat docker_ver )
    - NC_MINORVER=$( cat docker_ver | cut -c 1-4 )
    - NC_MAJORVER=$( cat docker_ver | cut -c 1-2 )
    - docker login docker.io -u fuzzymistborn -p $DOCKERHUB_PASS
    - docker login ghcr.io -u fuzzymistborn -p $GHCR_PASS
    - docker build -t fuzzymistborn/nextcloud-docker:latest -t fuzzymistborn/nextcloud-docker:$NC_FULLVER -t fuzzymistborn/nextcloud-docker:$NC_MINORVER -t fuzzymistborn/nextcloud-docker:$NC_MAJORVER -t ghcr.io/fuzzymistborn/nextcloud-docker:latest -t ghcr.io/fuzzymistborn/nextcloud-docker:$NC_FULLVER -t ghcr.io/fuzzymistborn/nextcloud-docker:$NC_MINORVER -t ghcr.io/fuzzymistborn/nextcloud-docker:$NC_MAJORVER .
    - docker push --all-tags fuzzymistborn/nextcloud-docker
    - docker push --all-tags ghcr.io/fuzzymistborn/nextcloud-docker

- name: Send TG Notification
  image: appleboy/drone-telegram
  settings:
    token:
      from_secret: tg_token
    to:
      from_secret: tg_id
    format: markdown
    message: "{{#success build.status}}✅  Docker Build for `{{repo.name}}` was *successful*!{{else}}❌  Docker Build for `{{repo.name}}` has *FAILED*!{{/success}} \n🌐  [Output]({{build.link}})\n📝  Commit: {{ commit.message }}"
  when:
    status: [ success, failure ]
