steps:
  - name: Build and push release
    image: fuzzymistborn/docker-alpine-skopeo:latest
    environment:
      GHCR_PASS:
        from_secret: ghcr_pass
      DOCKERHUB_PASS:
        from_secret: dockerhub_pass
    commands:
      - NC_FULLVER=$(cat docker_ver)
      - NC_MINORVER=$(cut -d. -f1,2 docker_ver)
      - NC_MAJORVER=$(cut -d. -f1 docker_ver)
      - docker login docker.io -u fuzzymistborn -p $DOCKERHUB_PASS
      - docker login ghcr.io -u fuzzymistborn -p $GHCR_PASS
      - docker build -t fuzzymistborn/nextcloud-docker:latest -t fuzzymistborn/nextcloud-docker:$NC_FULLVER -t fuzzymistborn/nextcloud-docker:$NC_MINORVER -t fuzzymistborn/nextcloud-docker:$NC_MAJORVER -t ghcr.io/fuzzymistborn/nextcloud-docker:latest -t ghcr.io/fuzzymistborn/nextcloud-docker:$NC_FULLVER -t ghcr.io/fuzzymistborn/nextcloud-docker:$NC_MINORVER -t ghcr.io/fuzzymistborn/nextcloud-docker:$NC_MAJORVER .
      - docker push --all-tags fuzzymistborn/nextcloud-docker
      - docker push --all-tags ghcr.io/fuzzymistborn/nextcloud-docker
      - docker rmi --force $(docker images -q fuzzymistborn/nextcloud*)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  - name: Notify Success
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: tg_token
      to:
        from_secret: tg_id
      format: markdown
      message: "✅  Docker Build for `${CI_REPO_NAME}` was *successful*!\n🌐  [Output](${CI_PIPELINE_URL})\n📝  Commit: ${CI_COMMIT_MESSAGE}"
    when:
      - event: tag
        status: [success]

  - name: Notify Failure
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: tg_token
      to:
        from_secret: tg_id
      format: markdown
      message: "❌  Docker Build for `${CI_REPO_NAME}` has *FAILED*!\n🌐  [Output](${CI_PIPELINE_URL})\n📝  Commit: ${CI_COMMIT_MESSAGE}"
    when:
      - event: tag
        status: [failure]

when:
  event: tag
