name: Docker

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set release version
        run: echo RELEASE=$( cat latest.txt ) >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          body: Nextcloud Server v${{ env.RELEASE }} release

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64
          tags: fuzzymistborn/nextcloud-docker:latest, fuzzymistborn/nextcloud-docker:${{ env.RELEASE }}
