name: Test

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get latest Nextcloud version
        id: get_version
        run: |
          nextcloud_ver=( $( curl -fsSL 'https://download.nextcloud.com/server/releases/' |tac|tac| \
            grep -oE 'nextcloud-[[:digit:]]+(\.[[:digit:]]+){2}' | \
            grep -oE '[[:digit:]]+(\.[[:digit:]]+){2}' | \
            sort -urV ) )
      
      - run: echo ${{ steps.get_version.outputs.nextcloud_ver }}
