name: Updater

on:
  workflow_dispatch:
  schedule:
    - cron:  '15 0 * * *'

jobs:
  run_updater:
    name: Run update.sh script
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run update.sh script
        run: ./update.sh

      - name: get last tag
        id: last_tag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: Set current version
        run: echo CURRENT_VERSION=${{ steps.last_tag.outputs.tag }} >> $GITHUB_ENV

      - name: Set latest version
        run: echo LATEST_VERSION=$( cat latest.txt ) >> $GITHUB_ENV

      - name: Commit files
        run: |
          if [ $(git diff HEAD | wc -l) -gt 1 ]
          then
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "GitHub Actions"
          git commit -a -m "Github Actions Update Dockerfile" || echo "Nothing to update"
          fi

      - name: Push changes
        uses: marvinpinto/action-automatic-releases@latest
        if: env.LATEST_VERSION != env.CURRENT_VERSION
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ env.LATEST_VERSION }}
          title: ${{ env.LATEST_VERSION }}